spring:
  cache:
    type: redis
  data:
    redis:
      host: localhost
      port: 6379
  jpa:
    open-in-view: false
    show-sql: true
#    properties:
#      hibernate:
#        show_sql: true
#        format_sql: true
#        use_sql_comments: true
#        jdbc:
#          time_zone: UTC

